exec-once = waybar
exec-once = hyprpaper
exec-once = hypridle
exec-once = brave
exec-once = discord
exec-once = nextcloud
exec-once = spotify-launcher

env = QT_QPA_PLATFORMTHEME,qt6ct
env = GTK_THEME,Breeze-Dark
