workspace = 1, monitor:DP-1
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:DP-1
workspace = 5, monitor:DP-1
workspace = 6, monitor:DP-2
workspace = 7, monitor:DP-2
workspace = 8, monitor:DP-2
workspace = 9, monitor:DP-2
workspace = 10, monitor:DP-2

windowrule = monitor DP-2, workspace 6, match:title .*DEBUG.*
windowrule = monitor DP-2, workspace 7, match:class com.obsproject.Studio
windowrule = monitor DP-2, workspace 8, match:class brave-browser
windowrule = monitor DP-2, workspace 9, match:class discord
windowrule = monitor DP-2, workspace 10, match:class Spotify
windowrule = match:fullscreen 1, border_color rgba(2AC3DEff)

bind = CTRL, P, exec, hyprshot -m output
bind = $mainMod, P, exec, hyprshot -m window
bind = CTRL SHIFT, P, exec, hyprshot -m region
